# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: whatsapppush

custom:
  templatesTableName: Templates
  bucketName: whatsapppush-recipient-bucket
  queueName: WhatsAppMessageQueue
  notificationTaskTableName: NotificationTask

# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x

  # you can overwrite defaults here
  #  stage: dev
  #  region: us-east-1

  environment:
    DDB_TEMPLATES_TABLE_NAME: ${self:custom.templatesTableName}
    S3_BUCKET_NAME: ${self:custom.bucketName}
    SQS_QUEUE_URL: 
      "Ref": whatsAppMessageQueue
    DDB_NOTIFICATION_TASK_TABLE_NAME: ${self:custom.notificationTaskTableName}

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["templatesTable", "Arn"] }
        - "Fn::GetAtt" : ["notificationTaskTable", "Arn"]
    - Effect: "Allow"
      Action:
        - s3:PutObject
      Resource:
        -  "Fn::Join": ["/", ["Fn::GetAtt": ["s3recipientBucket", "Arn"], "*"]]
    - Effect: "Allow"
      Action:
        - sqs:*
      Resource:
        - "Fn::GetAtt": ["whatsAppMessageQueue", "Arn"]

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  CreateTemplates:
    handler: handlers/template.createTemplates
    description: Function to handle business logic to create templates
    events:
      - http:
          path: templates
          method: post
  UpdateTemplates:
    handler: handlers/template.update
    description: Function to handle business logic to update template
    events:
      - http:
          path: templates/{user_id}/{template_id}
          method: put
  DeleteTemplates:
    handler: handlers/template.delete
    description: Function to handle business logic to delete templates
    events:
      - http:
          path: templates/{user_id}/{template_id}
          method: delete
  DetailsTemplates:
    handler: handlers/template.details
    description: Function to handle business logic to details templates
    events:
      - http:
          path: templates/{user_id}/{template_id}
          method: get
  ListTemplates:
    handler: handlers/template.list
    description: Function to handle business logic to list templates
    events:
      - http:
          path: templates/{user_id}
          method: get
  GetSignedUrl:
    handler: handlers/template.getSignedUrl
    description: Function to get s3 bucket signed url to upload the recipients file
    events:
      - http:
          path: /upload-url/{user_id}
          method: post
  CreateNotification:
    handler: handlers/notification.createNotification
    description: Function to create notification
    events:
      - http:
          path: notification
          method: post
  ListNotificationTasks:
    handler: handlers/notification.listNotificationTasks
    description: Function to list notifications
    events:
      - http:
          path: notification/{user_id}
          method: get
  SQSreceiver:
    handler: handlers/sqs-receiver.sqsReceiver
    timeout: 30
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - whatsAppMessageQueue
              - Arn
#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
resources:
  Resources:
    templatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.templatesTableName}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: template_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: template_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    notificationTaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.notificationTaskTableName}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: notification_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: notification_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    s3recipientBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: Private
        BucketEncryption:
          ServerSideEncryptionConfiguration: 
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - POST
                - PUT
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
    whatsAppMessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}
  Outputs:
    SQSUrl:
      Description: "SQS Url"
      Value: 
        "Ref": whatsAppMessageQueue

